/**
 * Script to generate seed.sql from the old template files.
 * Run with: node worker/db/generate-seed.mjs
 */

// We'll import the templates by directly parsing the TS files
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const oldTemplatesDir = resolve(__dirname, '../../../radreportai1/src/templates');

// Simple parser: extract template objects from .ts files
function parseTemplateFile(filePath) {
  const content = readFileSync(filePath, 'utf-8');
  const templates = {};
  
  // Match pattern: 'Template Name': `content`,
  const regex = /'([^']+)':\s*`([^`]+)`/g;
  let match;
  while ((match = regex.exec(content)) !== null) {
    templates[match[1]] = match[2];
  }
  return templates;
}

const modalities = {
  'Écho': parseTemplateFile(resolve(oldTemplatesDir, 'echo.templates.ts')),
  'IRM': parseTemplateFile(resolve(oldTemplatesDir, 'irm.templates.ts')),
  'TDM': parseTemplateFile(resolve(oldTemplatesDir, 'tdm.templates.ts')),
  'Radio': parseTemplateFile(resolve(oldTemplatesDir, 'radio.templates.ts')),
};

let sql = '-- Rad Report AI v2 — Default system templates (seeded from v1)\n';
sql += '-- Generated by worker/db/generate-seed.mjs\n\n';

let count = 0;
for (const [modality, templates] of Object.entries(modalities)) {
  sql += `-- ${modality} templates\n`;
  for (const [name, content] of Object.entries(templates)) {
    const escapedName = name.replace(/'/g, "''");
    const escapedContent = content.replace(/'/g, "''");
    sql += `INSERT INTO templates (user_id, modality, name, content) VALUES (NULL, '${modality}', '${escapedName}', '${escapedContent}');\n`;
    count++;
  }
  sql += '\n';
}

const outputPath = resolve(__dirname, 'seed.sql');
writeFileSync(outputPath, sql);
console.log(`Generated seed.sql with ${count} templates.`);
